site_name: Anders Bo Sørensen
docs_dir: .
site_dir: ../site
repo_url: https://github.com/absorensen/absorensen.github.io

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  language: en
  name: material
  icon:
    logo: fontawesome/solid/bolt
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

plugins:
  - glightbox
  - same-dir
  
extra:
  social:
    - icon: material/email
      link: mailto:anders-soerensen@hotmail.com
    - icon: fontawesome/brands/github
      link: https://www.github.com/absorensen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anders-bo-sorensen/

nav:
  - Home: README.md
  - Teaching: teaching.md
  - Code: code.md
  - CV: cv.md
  - Blog: 
    - blog/README.md
    - Test Post 1: blog/test_post_1.md
    - Test Post 2: blog/test_post_2.md